name: Liascript Automation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  run_liascript_automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or your preferred Node.js version

    - name: Install Node.js dependencies
      run: npm install

    - name: Generate Liascript PDF
      run: npm run generate-pdf # This runs your script/generate-pdf.js

    # For SCORM/IMS:
    # If Liascript provides a way to export to SCORM/IMS via a specific JavaScript function
    # or by wrapping your Liascript in a SCORM/IMS compatible template, you might need
    # to extend the Puppeteer script or use other tools here.
    # This is highly dependent on how you normally create SCORM/IMS packages from Liascript.
    # Often, SCORM/IMS generation involves packaging web content into a specific ZIP structure.

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: ${{ success() }}
      with:
        tag_name: ${{ inputs.version }}
        name: Liascript Release - ${{ inputs.version }}
        body: |
          Automated release of Liascript content for version ${{ inputs.version }}.
          Includes generated PDF and other packages.
        draft: false
        prerelease: false
        files: dist/* # Ensure your generation script places files here
