name: LiaScript Automation

on:
  workflow_dispatch:  # Allows manual triggering via GitHub's "Actions" tab

jobs:
  render-liascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git npm

      - name: Install LiaScript
        run: |
          npm install -g https://github.com/LiaScript/LiaScript.git
          echo "Installed LiaScript version:"
          lia --version
          echo "PATH: $PATH"
          echo "Global npm packages:"
          npm list -g --depth=0

      - name: Render LiaScript File
        run: |
          npx lia render week02_.md --out ./output --media ./media
          
      - name: Upload Rendered Output
        uses: actions/upload-artifact@v4
        with:
          name: lia-output
          path: ./output
