name: Build and Deploy LIA Script

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download LIA Script CLI
      run: |
        curl -L -o liascript https://github.com/LiaScript/cli/releases/latest/download/lia
        chmod +x liascript
        test -f liascript || (echo "Download failed" && exit 1)
        test -x liascript || (echo "liascript is not executable" && exit 1)

    - name: Convert LIA Script to HTML
      run: |
        mkdir -p dist
        ./liascript week02_.md -o dist/index.html

    - name: Copy media folder
      run: cp -r media dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
