name: LiaScript Automation

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  render-liascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Install LiaScript (correct method)
        run: |
          # Clone and install from source
          git clone https://github.com/LiaScript/LiaScript.git
          cd LiaScript
          npm install
          npm run build
          npm link
          cd ..
          
          # Verify installation
          echo "Node path: $(which node)"
          echo "NPM path: $(which npm)"
          echo "Lia path: $(which lia)"

      - name: Render LiaScript File
        run: |
          lia render week02_.md --out ./output --media ./media
          ls -la ./output  # Verify output files

      - name: Upload Rendered Output
        uses: actions/upload-artifact@v4
        with:
          name: lia-output
          path: ./output
