name: Build and Deploy LIA Script

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create output directory
      run: mkdir -p dist

    - name: Convert LIA Script to HTML via Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/slides liascript/cli \
          -i /slides/week02_.md -o /slides/dist/index.html

    - name: Copy media files
      run: cp -r media dist/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
