name: Convert LiaScript to HTML (Docker)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  convert-liascript:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build custom LiaScript Docker image
      run: |
        cat > Dockerfile << 'EOF'
        FROM node:18-alpine
        
        # Install LiaScript CLI globally
        RUN npm install -g @liascript/cli
        
        # Create working directory
        WORKDIR /workspace
        
        # Set entrypoint
        ENTRYPOINT ["liascript"]
        EOF
        
        docker build -t local-liascript .
        
    - name: Convert LiaScript files
      run: |
        # Convert all markdown files
        for file in *.md; do
          if [ -f "$file" ]; then
            echo "Converting $file..."
            docker run --rm -v $(pwd):/workspace local-liascript "$file"
          fi
        done
        
    - name: List output files
      run: |
        echo "Generated files:"
        ls -la *.html 2>/dev/null || echo "No HTML files generated"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: liascript-output
        path: '*.html'
